import uuid

from app.db.base import BaseDBModel
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.types import String


class SampleEntity(BaseDBModel):
    """Concrete test entity verifying BaseDBModel inheritance."""

    __tablename__ = "test_sample_entities"

    name: Mapped[str] = mapped_column(String(50), nullable=False)


def test_base_db_model_uuid_primary_key() -> None:
    """Verify that models inheriting from BaseDBModel have UUID primary keys."""
    entity = SampleEntity(name="LifeThread Goal Item")

    # UUID should be generated by default
    assert entity.id is not None
    assert isinstance(entity.id, uuid.UUID)


def test_base_db_model_attributes() -> None:
    """Verify that BaseDBModel includes id, created_at, and updated_at columns."""
    columns = SampleEntity.__table__.columns

    assert "id" in columns
    assert columns["id"].primary_key is True

    assert "created_at" in columns
    assert columns["created_at"].nullable is False

    assert "updated_at" in columns
    assert columns["updated_at"].nullable is False


def test_base_db_model_indexing() -> None:
    """Verify that id, created_at, and updated_at have indexes defined."""
    columns = SampleEntity.__table__.columns

    assert columns["id"].index is True
    assert columns["created_at"].index is True
    assert columns["updated_at"].index is True


def test_base_db_model_instantiation_with_custom_uuid() -> None:
    """Verify that models can accept an explicit UUID."""
    custom_uuid = uuid.uuid4()
    entity = SampleEntity(id=custom_uuid, name="Custom ID Item")
    assert entity.id == custom_uuid
